import Foundation

func check(_ value: Bool, _ message: String) {
    if !value { fatalError(message) }
}
let decoder = JSONDecoder()
let old = Data(#"["file:///Applications/A.app/","file:///Applications/B.app/"]"#.utf8)
let migrated = try decoder.decode([BrowserTarget].self, from: old)
check(migrated.map(\.app.lastPathComponent) == ["A.app", "B.app"], "legacy order survives")
check(migrated.allSatisfy { $0.profile == nil }, "legacy profiles are nil")
let new = Data(#"[{"app":"file:///Applications/A.app/","profile":"Profile 1"}]"#.utf8)
let targets = try decoder.decode([BrowserTarget].self, from: new)
check(targets[0].profile == "Profile 1", "profile is decoded")
check(migrated[0].shortcutKey(bundleIdentifier: "test.app") == "test.app", "legacy shortcut is unchanged")
check(targets[0].shortcutKey(bundleIdentifier: "test.app") == "test.app#Profile 1", "profile shortcut is distinct")
check((try? decoder.decode([BrowserTarget].self, from: Data("[42]".utf8))) == nil, "malformed targets rejected")
print("Migration checks passed")
check(LanguagePolicy.resolve(selection: "ru", preferred: ["de-DE"]) == "ru", "manual language")
check(LanguagePolicy.resolve(selection: "invalid", preferred: ["de-DE"]) == "de", "invalid selection falls back")
check(LanguagePolicy.resolve(selection: "", preferred: ["uk", "fr-CA"]) == "fr", "system preferred order")
check(LanguagePolicy.resolve(selection: "", preferred: ["zz"]) == "en", "English fallback")
check(!ProfilePathPolicy.isSafeComponent("../Profile 1"), "profile traversal rejected")
check(!ProfilePathPolicy.isSafeComponent("/tmp/x"), "absolute profile rejected")
check(ProfilePathPolicy.isSafeComponent("Profile 1"), "valid profile name")
let original = SourceTabIdentity(windowID: 1, tabID: 7, url: "https://example.com")
let changed = SourceTabIdentity(windowID: 1, tabID: 8, url: "https://example.com")
check(MovePolicy.shouldClose(openSucceeded: true, closeEnabled: true, original: original, current: original), "close original only after success")
check(!MovePolicy.shouldClose(openSucceeded: true, closeEnabled: true, original: original, current: changed), "do not close changed tab")
check(!MovePolicy.shouldClose(openSucceeded: false, closeEnabled: true, original: original, current: original), "failed open preserves source")
check(!MovePolicy.shouldClose(openSucceeded: true, closeEnabled: false, original: original, current: original), "close toggle respected")
check(!MovePolicy.shouldClose(openSucceeded: true, closeEnabled: true, original: original, current: nil), "missing source preserved")
let fixture = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
try FileManager.default.createDirectory(at: fixture, withIntermediateDirectories: true)
defer { try? FileManager.default.removeItem(at: fixture) }
let root = fixture.appendingPathComponent("root")
try FileManager.default.createDirectory(at: root, withIntermediateDirectories: true)
let escaped = root.appendingPathComponent("avatar")
try FileManager.default.createSymbolicLink(at: escaped, withDestinationURL: fixture)
check(!ProfilePathPolicy.contains(escaped.appendingPathComponent("outside.png"), in: root), "symlink escape rejected")
check(ProfilePathPolicy.contains(root.appendingPathComponent("Profile 1"), in: root), "child allowed")
check((try? SettingsPolicy.validate(["language": "ru", "profilesEnabled": true])) != nil, "valid settings accepted")
check((try? SettingsPolicy.validate(["language": "unknown"])) == nil, "unknown language rejected on import")
check((try? SettingsPolicy.validate(["browsers": "[42]"])) == nil, "malformed browser import rejected")
check((try? SettingsPolicy.validate(["profilesEnabled": 1])) == nil, "integer is not boolean")
check(try SettingsPolicy.validate(["AppleLanguages": ["ru"]]).isEmpty, "system settings excluded")
let suiteName = "BrowserinoTests." + UUID().uuidString
let defaults = UserDefaults(suiteName: suiteName)!
defer { defaults.removePersistentDomain(forName: suiteName) }
defaults.set(#"[{"directoryName":"Profile 1","displayName":"Work","isHidden":true}]"#, forKey: "chromeProfiles")
defaults.set(#"{"com.google.Chrome::Profile 1":"W"}"#, forKey: "shortcuts")
SettingsPolicy.migrateLegacyProfiles(defaults: defaults, chrome: URL(fileURLWithPath: "/Applications/Google Chrome.app"))
check(defaults.string(forKey: "profileNames")?.contains("Work") == true, "legacy alias preserved")
check(defaults.string(forKey: "shortcuts")?.contains("com.google.Chrome#Profile 1") == true, "legacy shortcut migrated")
let first = defaults.string(forKey: "hiddenBrowsers")
SettingsPolicy.migrateLegacyProfiles(defaults: defaults, chrome: URL(fileURLWithPath: "/Applications/Google Chrome.app"))
check(first == defaults.string(forKey: "hiddenBrowsers"), "migration idempotent")
print("Language, containment, move policy and settings checks passed")
check((try? SettingsPolicy.validate(["rules": #"[{"app":"file:///Applications/Safari.app","regex":".*","profile":7}]"#])) == nil, "numeric rule profile cannot erase rules")
check((try? SettingsPolicy.validate(["apps": #"[{"app":"file:///Applications/Safari.app","host":"","schemeOverride":"","profile":{}}]"#])) == nil, "object app profile cannot erase mappings")
let base = migrated[0]
let p1 = BrowserTarget(app: base.app, profile: "Profile 1")
let p2 = BrowserTarget(app: base.app, profile: "Profile 2")
check(TargetPolicy.visible([p1,p2], hidden: [base], profilesEnabled: true).isEmpty, "legacy hidden browser stays hidden after expansion")
check(TargetPolicy.visible([p1,p2], hidden: [base], profilesEnabled: false).isEmpty, "disabled profiles honor app-level hide")
let unhidden = TargetPolicy.toggle(base, targets: [p1,p2], hidden: [p1,p2])
check(TargetPolicy.visible([p1,p2], hidden: unhidden, profilesEnabled: false).count == 1, "app-level unhide restores collapsed row")
check(TargetPolicy.toggle(p1, targets: [p1,p2], hidden: [base]) == [p2], "unhide one profile preserves other hidden profile")
let legacyImported = try SettingsPolicy.validate(["chromeProfiles": #"[{"directoryName":"Profile 1","displayName":"Imported","isHidden":true}]"#, "chromeProfilesEnabled": false, "shortcuts": #"{"com.google.Chrome::Profile 1":"I"}"#])
check((legacyImported["profileNames"] as? String)?.contains("Imported") == true, "legacy import aliases normalized")
check((legacyImported["shortcuts"] as? String)?.contains("com.google.Chrome#Profile 1") == true, "legacy imported shortcut normalized")
check(legacyImported["profilesEnabled"] as? Bool == false, "legacy enabled flag imported")
print("Review regression checks passed")
check(TargetPolicy.isHidden(base, hidden: TargetPolicy.preserveHidden(oldTargets: [p1,p2], newTargets: [base], hidden: [p1,p2])), "all-hidden profiles stay hidden after collapse")
check(!TargetPolicy.isHidden(base, hidden: TargetPolicy.preserveHidden(oldTargets: [p1,p2], newTargets: [base], hidden: [p1])), "partially visible browser stays visible after collapse")
check((try? SettingsPolicy.validate(["KeyboardShortcuts_moveCurrentTab": #"{"carbonKeyCode":7,"carbonModifiers":4096}"#])) != nil, "move shortcut validates")
check((try? SettingsPolicy.validate(["KeyboardShortcuts_moveCurrentTab": #"{"carbonKeyCode":-1,"carbonModifiers":4096}"#])) == nil, "invalid move key code rejected")
let legacyRule = try decoder.decode(Rule.self, from: Data(#"{"regex":".*","app":"file:///Applications/Google Chrome.app","profileDirectory":"Profile 1"}"#.utf8))
check(legacyRule.profile == "Profile 1", "legacy Chrome rule target retained")
check((try? SettingsPolicy.validate(["rules": #"[{"regex":".*","app":"file:///Applications/Google Chrome.app","profileDirectory":"../escape"}]"#])) == nil, "legacy rule traversal rejected")
